site_name: Tech Space

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.math
    - search.highlight
    - search.share
  # toc_depth: 3

  palette:
    - scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-sunny

    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-night

nav:
  - Home: index.md
  - Mini Books:
      - Pydantic:
          - Introduction: Mini Books/Pydantic/Introduction.md
          - Chapter 1: Mini Books/Pydantic/Chapter 1.md
          - Chapter 2: Mini Books/Pydantic/Chapter 2.md
      - Transformers:
          - Self Attention: Mini Books/Transformers/Self Attention/Self Attention.md
      - Kubernetes:
          - Why Kubernetes: Mini Books/Kubernetes/Why Kubernetes.md
          - Pod: Mini Books/Kubernetes/Pod.md
          - Kubernetes Architecture: Mini Books/Kubernetes/Kubernetes Architecture.md
          - What is deployment: Mini Books/Kubernetes/What is deployment.md
          

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 3

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2025 Paritosh Sharma

extra_css:
  - stylesheets/extra.css  # optional
