site_name: Paritosh's Tech Universe

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.math
    - search.highlight
    - search.share
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.path
    - navigation.indexes

  # toc_depth: 3

  palette:
    - scheme: default
      primary: cyan
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: index.md
  - Mini Books:
      - Books:
          - Pydantic:
              - Introduction: Mini Books/Pydantic/Introduction.md
              - Chapter 1: Mini Books/Pydantic/Chapter 1.md
              - Chapter 2: Mini Books/Pydantic/Chapter 2.md

          - Transformers:
              - Self Attention: Mini Books/Transformers/Self Attention/Self Attention.md

          - Kubernetes:
              - Why Kubernetes: Mini Books/Kubernetes/Why Kubernetes.md
              - Pod: Mini Books/Kubernetes/Pod.md
              - Kubernetes Architecture: Mini Books/Kubernetes/Kubernetes Architecture.md
              - What is deployment: Mini Books/Kubernetes/What is deployment.md
              - Service: Mini Books/Kubernetes/Service.md

          - JavaScript:
              - Immediately Invoked Function Expressions (IIFE): Mini Books/JavaScript/01. Immediately Invoked Function Expressions (IIFE).md
              - Call Stack: Mini Books/JavaScript/02. Call Stack.md
              - Control Flow: Mini Books/JavaScript/03. Control Flow.md
              - For Loop: Mini Books/JavaScript/04. For Loop.md
              - While and do-while Loops: Mini Books/JavaScript/05. while and do-while Loops.md
              - Higher Order Loops: Mini Books/JavaScript/06. Higher Order Loops and Array Iteration.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 3

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/collapsible-toc.js

copyright: Copyright &copy; 2025 Paritosh Sharma

extra_css:
  - assets/extra.css
